sudo: false
dist: trusty
language: go
go:
- "1.11"
before_script:
  - wget https://github.com/goreleaser/goreleaser/releases/download/v0.101.0/goreleaser_Linux_x86_64.tar.gz -O /tmp/goreleaser.tar.gz
  - tar -xvf /tmp/goreleaser.tar.gz
  - mv /tmp/goreleaser /usr/local/bin/
script:
- make tools
- make
after_success:
- if [[ -n "$TRAVIS_TAG" ]]; then make release; fi
notifications:
  email: true
